Mention context commitment
jedisct1/draft-aegis-aead pull request #21
Opened 2021-12-14 16:33 UTC by samuel-lucas6

Addresses #19. May need some rewording. Should I add a hyphen for 'context-commitment' to be consistent with 'key-commitment'?

2021-12-14 17:39 UTC, fscoto requested changes
Side note: Shouldn't much of this be mirrored in the Security Considerations section?

2021-12-14 17:39 UTC, fscoto commented on draft-denis-aegis-aead.md
> +At the same time, the AEGIS cipher family offers optimal performance on CPUs with hardware support for parallelizable AES block encryption. Its performance exceeds that of AES-GCM{{AEGIS}} significan
Could I ask you to choose either "context-commitment" or "key commitment"? I have no strong feelings in either direction, but inconsistency makes for a frustrating reading.

2021-12-14 17:39 UTC, fscoto commented on draft-denis-aegis-aead.md
> +Moreover, AEGIS is context committing, meaning different associated data for a (key, nonce) pair results in a different keystream for encryption, not just a different authentication tag. This provide
Is this clear to a reader coming in without the context in #19? “This provides some resistance against key reuse in different contexts.” This seems to go approximately nowhere; what is a “context” in this context? The issue with “context” is that it's an overloaded word in that it refers to:

1. an opaque context object in every cryptography API under the sun;
2. semantically different instantiations of the same cryptographic operation (cf. RFC 8032 § 8.3);
3. circumstances that form a setting for a concept or event;
4. regions of text around a certain other passage of text.

I feel like the wording here invites conflating these meanings. At least I needed a section to assign this usage to meaning 2. YMMV, maybe I'm the dense one here.

2021-12-14 18:40 UTC, samuel-lucas6 commented on draft-denis-aegis-aead.md
> +At the same time, the AEGIS cipher family offers optimal performance on CPUs with hardware support for parallelizable AES block encryption. Its performance exceeds that of AES-GCM{{AEGIS}} significan
I agree. My preference would be without the hyphen.

2021-12-14 18:49 UTC, samuel-lucas6 commented on draft-denis-aegis-aead.md
> +Moreover, AEGIS is context committing, meaning different associated data for a (key, nonce) pair results in a different keystream for encryption, not just a different authentication tag. This provide
I see what you mean. I think context committing makes sense because the associated data is often used for context information. How about 'This provides some resistance against key reuse when distinct associated data is used' or 'when using distinct associated data'?

2021-12-14 19:30 UTC, fscoto commented on draft-denis-aegis-aead.md
> +Moreover, AEGIS is context committing, meaning different associated data for a (key, nonce) pair results in a different keystream for encryption, not just a different authentication tag. This provide
Personally, I'm in favor of the third option (“when encrypting data in different contexts”). The first two drop the word entirely, losing the connection to two paragraphs down where context commitment is touted as a feature; the fourth one has a vaguely defined, newly minted term "context information.

2021-12-14 19:33 UTC, fscoto commented on draft-denis-aegis-aead.md
> +While this may be mitigated by means of inserting a padding block in the aforementioned algorithms, this workaround comes with additional processing cost and must itself be carefully constructed to r
*This* hyphen [has grammatical meaning because it is a phrasal adjective](https://en.wikipedia.org/wiki/English_compound#Hyphenated_compound_modifiers); please leave this hyphen unchanged.

2021-12-14 19:49 UTC, jedisct1 commented
The way I understand it, Security Considerations describe how to use the functions safely rather than the functions properties.

We can discuss the limitations of context commitment - what is being absorbed is `pad(ad)||msg` and context separation only happens at finalization - in that section, though.

2021-12-14 19:57 UTC, fscoto commented
> The way I understand it, Security Considerations describe how to use the functions safely rather than the functions properties.

Helpfully, [BCP 72](https://www.rfc-editor.org/info/bcp72) defines what the Security Considerations must and should describe. In particular, the section must describe which attacks are in scope and out of scope, where the in-scope section needs to detail both which attacks the protocol is susceptible to and which ones the protocol does protect against. This doesn't cleanly apply to an informational description of a pure algorithm as opposed to a protocol, but considering we mention key commitment and context commitment in the introduction, they do need to be fleshed out or at least brought up again in the security considerations section.

I could make a draft tomorrow to address this in particular.

2021-12-14 20:35 UTC, samuel-lucas6 commented on draft-denis-aegis-aead.md
> +Moreover, AEGIS is context committing, meaning different associated data for a (key, nonce) pair results in a different keystream for encryption, not just a different authentication tag. This provide
Thanks for the feedback. I've changed it to that.

2021-12-14 20:51 UTC, samuel-lucas6 commented on draft-denis-aegis-aead.md
> +While this may be mitigated by means of inserting a padding block in the aforementioned algorithms, this workaround comes with additional processing cost and must itself be carefully constructed to r
I see what you mean. I've restored the hyphens for key committing. 

I was following [Gueron's](https://eprint.iacr.org/2020/1153.pdf) paper. The [Message Franking](https://eprint.iacr.org/2017/664.pdf) and [Fast Message Franking](https://eprint.iacr.org/2019/016.pdf) papers also don't use a hyphen for compactly committing AEAD. Grammatically speaking, I think you're probably correct, but I expect some people wouldn't use a hyphen still.

2021-12-15 03:39 UTC, fscoto approved these changes
LGTM now

2021-12-15 03:40 UTC, merged