Cite Vaudenay and Vizár's paper
jedisct1/draft-aegis-aead pull request #30
Opened 2022-01-05 09:43 UTC by jedisct1

The paper highlights the importance of not leaking decrypted data without tag verification.

Suggested by Daniel Bleichenbacher, thanks!

2022-01-05 10:37 UTC, samuel-lucas6 commented
Is it worth using [this](https://eprint.iacr.org/2017/1147.pdf) link instead? Then the PDF opens in the browser.

2022-01-05 11:15 UTC, fscoto commented
The publication story of this paper is interesting if hopelessly chaotic. According to https://infoscience.epfl.ch/record/264823/, this paper is supposedly published in  Applied Cryptography and Network Security 2018 (LNCS vol. 10892), pp. 476-494. Following the DOI link, we reach https://link.springer.com/chapter/10.1007/978-3-319-93387-0_25, where you may note that the paper's title is “Can Caesar Beat Galois?”

I can't tell which one is the authoritative version of the paper. Should someone reach out to the (according to IACR ePrint) corresponding author Damian Vizár and inquire as to which version to cite and if there are substantial differences other than the pagination? I don't feel comfortable citing into the void. If the conference version is authoritative, we'll have to link to paywalled content, but personally I don't have an issue with that.

Re @samuel-lucas6: If anything, shouldn't the link be https://infoscience.epfl.ch/record/264823/, where it's *not* a link to a PDF and instead the abstract? I distinctly recall mobile users struggling with PDF links and not appreciating such links without warning.

2022-01-05 11:36 UTC, samuel-lucas6 commented
> Re @samuel-lucas6: If anything, shouldn't the link be https://infoscience.epfl.ch/record/264823/, where it's not a link to a PDF and instead the abstract? I distinctly recall mobile users struggling with PDF links and not appreciating such links without warning.

Interesting point, although the AEGIS link is to a PDF since there's no alternative. The Partitioning Oracle Attacks link is to the abstract, but that's useful in that there's also a video and slides. However, that link means not citing a paywalled article, so I'd go with that.

2022-01-05 15:12 UTC, fscoto commented
> However, that link means not citing a paywalled article, so I'd go with that.

What matters is whether it's the *correct* article. There's no point in citing outdated (and possibly wrong) material. So should I just try to reach out and ask the authors for clarification?

2022-01-05 15:59 UTC, samuel-lucas6 requested changes
I suggest changing the link to https://eprint.iacr.org/2017/1147.

2022-01-05 16:12 UTC, fscoto commented
> The paywalled content is shorter (18 vs 24 pages).

Are they the same page size and line height though? It's trivial to get different page counts with different formatting. I'm *strongly* hesitant on relying on the IACR ePrint version because one would expect that the published version actually got reviewer; the IACR ePrint version is either a pre-print (and there were relevant changes in the review) or is a post-production (fixing issues they found after publication) and we just don't know which one it is.

2022-01-05 16:21 UTC, samuel-lucas6 commented
> Are they the same page size and line height though? It's trivial to get different page counts with different formatting. I'm strongly hesitant on relying on the IACR ePrint version because one would expect that the published version actually got reviewer; the IACR ePrint version is either a pre-print (and there were relevant changes in the review) or is a post-production (fixing issues they found after publication) and we just don't know which one it is.

The paywalled version is missing several sections from the end, and the references are less spaced. Their comment in the paywalled version suggests it's a reduced version of the paper with formatting changes for that journal and in response to feedback.

2022-01-06 21:45 UTC, jedisct1 commented
I reached out to Damian as well. Haven't heard back from him either so far.

The second version doesn't introduce new or different results. So, I'd be inclined to use the non-paywalled version for now. As the AEGIS draft is being reviewed, it will be easier for everybody to look at the papers we reference.

If Damian later suggests we should use the paywalled version, it certainly won't be too late to do it.

Meanwhile, the URL has been changed to the IACR hosted one.

2022-01-07 04:34 UTC, merged

2022-01-07 04:35 UTC, fscoto commented
I continue to disagree on the paywall being a blocker, but considering neither of us has heard from the author in the meantime and @samuel-lucas6 observing several additional sections in the IACR ePrint version, the latter is *likely* the correct one and I agree with the change.