Add MILP-based evaluation of AEGIS
jedisct1/draft-aegis-aead pull request #72
Opened 2023-04-04 09:30 UTC by jedisct1

Fixes #71

2023-04-04 09:57 UTC, jedisct1 commented
Martin's scripts to build HTML files seems to be currently broken :/

2023-04-04 12:57 UTC, samuel-lucas6 requested changes

2023-04-04 12:57 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Security analyses of AEGIS can be found in Chapter 4 of {{AEGIS}}, in {{Min14}}, in {{ENP19}}, in {{LIMS21}}, in {{JLD21}}, and in {{SHI23}}.
Think this should be `{{STSI23}}` for Shiraya, Takeuchi, Sakamoto, and Isobe.

2023-04-04 12:57 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +    rc: "Institution of Engineering and Technology"
Should this be 'IET Information Security'?

2023-04-04 12:57 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +        org: University of Hyogo, Kobe, Japan.
Previously also had '; National Institute of Information and Communications Technology' if you look at `LIMS21`.

2023-04-04 12:57 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +        org: University of Hyogo, Kobe, Japan.
Don't think ', Kobe, Japan.' is needed based on previous references (e.g. `LIMS21`).

2023-04-04 14:03 UTC, jedisct1 commented
Thank you Samuel!

These changes have been made.

2023-04-04 19:37 UTC, samuel-lucas6 requested changes
Thanks for the changes. Two little things.

There are a few inconsistencies for the other references (e.g. no target, no page numbers, specific vs year for dates) that can probably be tidied up in a separate PR.

2023-04-04 19:37 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +    rc: "Institution of Engineering and Technology"
Sorry to be annoying, but I think this should be "IET Information Security, 2023, pp. 1-10" based on [this](https://ietresearch.onlinelibrary.wiley.com/action/showCitFormats?doi=10.1049%2Fise2.12109) and the other rcs.

2023-04-04 19:37 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +        org: University of Hyogo; National Institute of Information and Communications Technology; PRESTO, Japan Science and Technology Agency
'; PRESTO, Japan Science and Technology Agency' can be removed as it isn't mentioned in this paper.

2023-04-05 08:56 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +        org: University of Hyogo; National Institute of Information and Communications Technology; PRESTO, Japan Science and Technology Agency
Thanks Samuel!

Chronologically ordering the references may also be a good thing to do, but that can be done in another PR.

2023-04-05 08:57 UTC, merged