Add support for 256-bit tags
jedisct1/draft-aegis-aead pull request #76
Opened 2023-04-06 18:08 UTC by jedisct1

Update the test vectors and implementations accordingly.

Once we have a proof that AEGIS is context committing, we can expand on when to use 128 vs 256 bit tags in the context of commitment.

2023-04-07 19:47 UTC, samuel-lucas6 requested changes
Nice work! A few style things and good to go.

2023-04-07 19:47 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- AEGIS-256, which has a 256-bit key, a 256-bit nonce, a 768-bit state, a 128-bit or 256-bit authentication tag, and processes 128-bit input blocks.
What are your thoughts on '128- or 256-bit'? It feels more consistent with '(128 or 256 bits)' to me.

2023-04-07 19:47 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +If tag_length == 16: # 128 bits
The current pseudocode uses lowercase `if` and `else` (e.g. [here](https://jedisct1.github.io/draft-aegis-aead/draft-irtf-cfrg-aegis-aead.html#section-3.2-9)).

2023-04-07 19:47 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys. Assuming AEGIS is key-committing, finding equivalent keys is expected to require ~2<sup>64<sup> attempts with a 128-bit authentication tag, and ~
Missing `</sup>` with the `~2<sup>64<sup>`. Last comma before the 'and' can also be removed.

2023-04-08 13:32 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- AEGIS-256, which has a 256-bit key, a 256-bit nonce, a 768-bit state, a 128-bit or 256-bit authentication tag, and processes 128-bit input blocks.
Indeed, `128- or 256-bit` looks better. Changed, thanks!

2023-04-08 13:33 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys. Assuming AEGIS is key-committing, finding equivalent keys is expected to require ~2<sup>64<sup> attempts with a 128-bit authentication tag, and ~
Done.

2023-04-08 13:35 UTC, merged