Mention that the key can be erased after initialization
jedisct1/draft-aegis-aead pull request #96
Opened 2023-09-12 19:07 UTC by jedisct1

Fixes #95

2023-09-12 20:46 UTC, samuel-lucas6 requested changes
A few tweaks. Thanks for doing the PR.

2023-09-12 20:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Unlike most other AES-based AEAD constructions, leaking a state does not leak the key nor the previous states.
Drop the second `the`?

> leaking a state does not leak the key nor previous states.

2023-09-12 20:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Finally, an AEGIS key is not required any more after the setup phase, and there is no key schedule. In order to mitigate cold bool attacks, ephemeral keys can be thus be erased from memory very quick
- Could remove `any more`? If staying, it should probably be one word `anymore`.
- Could be reworded to `an AEGIS key can be erased after the setup phase` or `an AEGIS key does not need to be stored in memory after the setup phase`. The second half would obviously have be rephrased then.
- Could change `In order to` to just `To mitigate...`
- `can be thus be` has a typo and `thus` can be dropped.

I would probably write:

> Finally, an AEGIS key is not required after the setup phase, and there is no key schedule. Thus, ephemeral keys can be erased from memory before any data has been encrypted or decrypted, mitigating cold boot attacks.

2023-09-12 20:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Regardless of the variant, the `key` and `nonce` are only required by the `Init` function; other functions only depend on the resulting state. As a result, implementations can overwrite ephemeral key
This is good, but I think `Therefore,` instead of `As a result,` might sound better due to `resulting state`:

> other functions only depend on the resulting state. Therefore, implementations can overwrite ephemeral keys

2023-09-13 12:40 UTC, jedisct1 commented
Thanks a lot for your suggestions, @samuel-lucas6 !

2023-09-13 19:22 UTC, samuel-lucas6 approved these changes

2023-09-13 19:23 UTC, merged