Update the claims on key commitment after the Isobe & Rahman analysis
jedisct1/draft-aegis-aead pull request #97
Opened 2023-10-02 17:01 UTC by jedisct1

TBD: add a link to the paper will of course be added after it has been published.

2023-10-03 19:42 UTC, samuel-lucas6 requested changes

2023-10-03 19:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys, nonces, or associated data. But AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-
> `(ad, ct, tag)`

Is it worth writing these in full? The rest of the section doesn't refer to shorthand.

2023-10-03 19:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys, nonces, or associated data. But AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-
I'd probably replace `But AEGIS` with `However, AEGIS`. I just don't like starting sentences with 'but'. Having said that, however is used below so maybe bad idea. Could make it one long sentence:

> , or associated data, but AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-entropy keys such as passwords.

2023-10-03 19:45 UTC, samuel-lucas6 commented
Bit unfortunate it's not fully committing. Good that lots of commitment papers are coming out now though. Interested to have a look at this one.

2023-10-03 21:49 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys, nonces, or associated data. But AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-
> > `(ad, ct, tag)`
> 
> Is it worth writing these in full? The rest of the section doesn't refer to shorthand.

In the introduction, these are written in full, because they haven't been defined yet. But in the security considerations, using the same names as in the function definitions seems a little bit clearer to me. We know exactly what they refer to.

2023-10-03 21:50 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys, nonces, or associated data. But AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-
> > auccessfully
> 
> Typo

Good catch, thanks!

2023-10-03 21:51 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +An authentication tag may verify under multiple keys, nonces, or associated data. But AEGIS is assumed to be key committing in the receiver-binding game, preventing common attacks when used with low-
> I'd probably replace `But AEGIS` with `However, AEGIS`. I just don't like starting sentences with 'but'. Having said that, however is used below so maybe bad idea. Could make it one long sentence:

I wanted to avoid the `however` repetition. Let's go for the long sentence, then.

2023-10-03 21:52 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +However, it is NOT fully committing, as the key doesn't commit to the associated data: with the ability to also alter `ad`, it is possible to efficiently find multiple keys that will verify the same
Rephrased, then :)

2023-10-03 21:57 UTC, jedisct1 commented
Things would have been easier if it were an ideal permutation. But not committing to the AD is not the end of the world. In most real-world protocols, the AD is specified by the protocol itself, and is rarely as large as the AEGIS state size. This is still a substantial improvement over poly-based authentication schemes.

2023-10-04 20:22 UTC, samuel-lucas6 approved these changes
Thanks for the PR and changes Frank!

2023-10-04 20:23 UTC, merged

2023-10-04 20:27 UTC, samuel-lucas6 commented
The paper is on [ePrint](https://eprint.iacr.org/2023/1495) now but thought that could be saved for a separate PR. We also need to credit them in the Acknowledgments.