Document how to use AEGIS as a stream cipher
jedisct1/draft-aegis-aead pull request #99
Opened 2023-10-03 23:34 UTC by jedisct1

Here's a proposal to use AEGIS as a stream cipher.

Only the function that produces the keystream is documented.

How to use that for unauthenticated encryption is intentionally omitted, so we don't have to explain why that should generally never be used. Doing so when you really need it should be obvious to people who really need it.

And how to compute the mask for QUIC header protection becomes simpler.

2023-10-04 20:19 UTC, samuel-lucas6 requested changes

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Stream(length, key [, nonce])
This confused me initially, and the space after `key` bothers me. Maybe we should just specify the nonce here normally since it's listed in `Inputs:` below.

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `len`: the length of the keystream to generate.
`len` is inconsistent with `Stream(length`. Perhaps use shortened due to `ad_len_bits`/`msg_len_bits`?

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +stream, tag = Encrypt(ZeroPad({}, len), {}, key, nonce)
I think we should define `{}` in the `Conventions and Definitions` section to avoid confusion, or we use something like `""` as you did lower down (still defining it).

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Instead of relying on the generic `Encrypt` function, implementations may take advantage of the fact that the finalization step is not needed.
> implementations may take advantage of the fact that the finalization step is not needed.

This feels like it could be shortened. Something like `implementations can skip the finalization step` or `implementations do not need the finalization step`.

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +After initialization, the `Update` function is called with constant paramters. This may allow further optimizations.
> paramters

Typo

Could merge the sentences:

> After initialization, the `Update` function is called with constant parameters, allowing further optimizations.

Is the further optimisations referring to skipping finalisation?

2023-10-04 20:19 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ciphertext[0..16]`: the first 16 bytes of the DTLS ciphertext
It's not visible for a comment, but maybe this should be updated to reference the `Stream` function:

> the mask is generated using the AEGIS `Encrypt` function

2023-10-04 21:29 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `len`: the length of the keystream to generate.
Good catch.

2023-10-04 21:31 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +stream, tag = Encrypt(ZeroPad({}, len), {}, key, nonce)
`""` is a bit misleading, as these parameters are not strings.

How would you define `{}`? "An empty bit array"?

2023-10-04 21:34 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +After initialization, the `Update` function is called with constant paramters. This may allow further optimizations.
> Is the further optimisations referring to skipping finalisation?

Correct. Do you think `further` should be removed?

2023-10-04 21:35 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ciphertext[0..16]`: the first 16 bytes of the DTLS ciphertext
Absolutely!

2023-10-04 21:38 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +Stream(length, key [, nonce])
Yeah, I was looking for a way to signal that the nonce was optional, but it can indeed be confusing. Removed.

2023-10-05 16:43 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +stream, tag = Encrypt(ZeroPad({}, len), {}, key, nonce)
Yeah I hear you. That sounds good. Only other option I can think of would be 'A zero-length bit array', but that sounds worse.

2023-10-05 16:45 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +After initialization, the `Update` function is called with constant paramters. This may allow further optimizations.
After rereading, further seems appropriate.

2023-10-05 16:51 UTC, jedisct1 commented
Thank you Samuel!

Your feedback should have been addressed.

2023-10-05 16:52 UTC, samuel-lucas6 approved these changes

2023-10-05 16:53 UTC, merged